program: main.py
method: random
metric:
  name: elbo_loss
  goal: minimize
parameters:
  optimizer:
    value: adam
  scheduler:
    value: reduce_lr
  hidden_dim:
    values: [96, 128, 148]
  hidden_sub_dim:
    values: [1, 10, 20, 30, 40, 50]
  num_epochs:
    values: [10, 50, 75, 100, 150, 200]
  batch_size:
    values: [1, 64, 128, 256, 512]
  weight_decay:
    distribution: uniform
    min: 0
    max: 0.1
  learning_rate:
    distribution: uniform
    min: 0
    max: 0.1
  num_workers:
    value: 22
  beta:
    value: 1
early_terminate:
  type: hyperband
  max_iter: 6
  s: 2
  eta: 3

  # encoder:
  #   value: vanilla
  # decoder: 
  #   value: vanilla
  # test_bool:
  #   value: True
  # log_metrics: 
  #   value: True
  # watch_loss:
  #   value: True
    
# distribution: q_log_uniform
# min: math.log(32)
# max: math.log(256)
# q: 1